# Generated by Django 2.1.2 on 2018-11-06 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_auto_20181105_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('setar_nfe', 'Usuário pode alterar o parametro da NF-e'), ('permissao2', 'Permissão 2'), ('permissao3', 'Permissão 3'))},
        ),
    ]
