# Generated by Django 2.1.2 on 2018-11-06 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_auto_20181106_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('setar_nfe', 'Usuário pode alterar o parametro da NF-e'), ('ver_dashboard', 'Pode visualizar o dashboard'), ('permissao3', 'Permissão 3'))},
        ),
    ]
