# Generated by Django 2.1.2 on 2018-11-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20180210_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=models.TextField(default='N/A'),
        ),
    ]
