# Generated by Django 2.1.2 on 2018-11-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_auto_20181101_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
