# Generated by Django 2.1.2 on 2018-11-03 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_auto_20181103_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='venda',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='pessoa',
        ),
        migrations.DeleteModel(
            name='ItemPedido',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
