# Generated by Django 2.1.2 on 2018-11-06 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_auto_20181103_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('deletar_cliente', 'Deletar Cliente'),)},
        ),
    ]
